// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY152nkyYV-oHo8EIsEXQS92pOGUzoSKo',
    appId: '1:1086689583950:web:6f6ce7f778802f835bf41f',
    messagingSenderId: '1086689583950',
    projectId: 'movesapp-de9e6',
    authDomain: 'movesapp-de9e6.firebaseapp.com',
    storageBucket: 'movesapp-de9e6.firebasestorage.app',
    measurementId: 'G-EE56DLZF4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjaLbpFx2yswXwGd8uapZxxBf7OH58h0o',
    appId: '1:1086689583950:android:8af347585798bb3a5bf41f',
    messagingSenderId: '1086689583950',
    projectId: 'movesapp-de9e6',
    storageBucket: 'movesapp-de9e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfj6ixDvLIG_f7-EWY-04RxvJK3qw8vlU',
    appId: '1:1086689583950:ios:3c40241484f9c88b5bf41f',
    messagingSenderId: '1086689583950',
    projectId: 'movesapp-de9e6',
    storageBucket: 'movesapp-de9e6.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfj6ixDvLIG_f7-EWY-04RxvJK3qw8vlU',
    appId: '1:1086689583950:ios:3c40241484f9c88b5bf41f',
    messagingSenderId: '1086689583950',
    projectId: 'movesapp-de9e6',
    storageBucket: 'movesapp-de9e6.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY152nkyYV-oHo8EIsEXQS92pOGUzoSKo',
    appId: '1:1086689583950:web:cdc94b352eb4f8cb5bf41f',
    messagingSenderId: '1086689583950',
    projectId: 'movesapp-de9e6',
    authDomain: 'movesapp-de9e6.firebaseapp.com',
    storageBucket: 'movesapp-de9e6.firebasestorage.app',
    measurementId: 'G-25LT7MRNQD',
  );
}